name: Wellesley Cosmetic Surgery
favicon: null
layout_spectrum: 0.74143
typography_spectrum: 0.99478
title: A premier face lifting and breast enhancement cosmetic surgery practice
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1860ac'
    - '#bcd0dc'
    - '#868a7b'
    - '#f9fefe'
    - '#000200'
  brandStrength: 0.8440590868704021
  lightness: 0.4255840783007443
  saturation: 0.9114147326909006
  rhythmicContrast: 0.2673704659100622
purpose: []
